name: Lost & Found Pipeline
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: push

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
          
      - name: Scan with SonarQube
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
      - name: Scan dependencies with Snyk
        uses: snyk/actions/node@v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Scan code with Snyk
        uses: snyk/actions/node@v1.0.0
        with:
          command: code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  test:
    name: Testing
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - run: npm ci
      - run: npm test -- --runInBand

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: coverage/
  
  build:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/deploy/production'
    name: Building the app
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t lost-and-found-api:${{ github.run_number }} .

      - name: Save Docker image
        run: docker save -o image.tar lost-and-found-api:${{ github.run_number }}

      - name: Upload Docker image
        if: github.ref == 'refs/heads/deploy/production'
        uses: actions/upload-artifact@v4
        with:
          name: lost-and-found-api-image
          path: image.tar
  
  deliver:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/deploy/production'

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: lost-and-found-api-image

      - name: Load Docker image
        run: docker load -i image.tar

      - name: Login to Docker Hub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          printf '%s' "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      - name: Tag Docker image
        run: |
          docker tag lost-and-found-api:${{ github.run_number }} "$DOCKERHUB_USERNAME/lost-and-found-api:${{ github.run_number }}"

      - name: Push Docker image
        run: docker push "$DOCKERHUB_USERNAME/lost-and-found-api:${{ github.run_number }}"

  deploy:
    name: Deploy image to AWS
    runs-on: ubuntu-latest
    needs: deliver
    if: github.ref == 'refs/heads/deploy/production'

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Check AWS authentication
        run: aws sts get-caller-identity

      - name: Check EC2 status in SSM
        env:
          EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        
        run: |
          aws ssm describe-instance-information \
          --filters "Key=InstanceIds,Values=$EC2_INSTANCE_ID" \
          --query "InstanceInformationList[].{Instance:InstanceId,Status:PingStatus}" \
          --output table

  e2e-and-performance:
    if: github.ref == 'refs/heads/deploy/production'
    name: E2E and performance tests against stagings
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."